create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  username text not null,
  phone text,
  role text not null default 'customer' check (role in ('admin', 'customer')),
  profile_picture text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  user_id uuid unique references public.users(id) on delete cascade,
  name text not null,
  phone text,
  email text,
  address text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references public.users(id) on delete cascade,
  customer_name text,
  customer_phone text,
  device_type text,
  brand text,
  model text,
  serial_number text,
  issue_description text,
  preferred_date text,
  preferred_time text,
  status text not null default 'pending',
  notes text,
  diagnosis_category text,
  diagnosis_result text,
  diagnosis_cf_percentage double precision,
  diagnosis_symptoms text,
  device_photo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.bookings
  add column if not exists customer_email text;

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  service_code text unique not null,
  origin_booking_id bigint references public.bookings(id) on delete set null,
  customer_id uuid not null references public.users(id) on delete cascade,
  customer_name text,
  customer_phone text,
  customer_email text,
  device_type text,
  device_brand text,
  model text,
  serial_number text,
  problem text,
  spare_parts_used jsonb,
  initial_detail text,
  service_detail text,
  status_note text,
  estimated_cost double precision not null default 0,
  cost double precision not null default 0,
  technician text,
  status text not null default 'pending',
  payment_method text,
  payment_choice text,
  payment_status text not null default 'pending',
  finance_recorded boolean not null default false,
  completed_at timestamptz,
  taken_at timestamptz,
  status_history jsonb not null default '[]'::jsonb,
  device_photo text,
  receipt_photo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  service_id bigint references public.services(id) on delete cascade,
  amount double precision not null default 0,
  payment_status text not null default 'pending',
  payment_method text,
  transaction_date timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.spare_parts (
  id bigint generated by default as identity primary key,
  part_name text not null,
  category text,
  category_code text,
  part_code text,
  stock_quantity integer not null default 0,
  minimum_stock integer not null default 5,
  unit_price double precision not null default 0,
  supplier text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


alter table public.spare_parts add column if not exists category_code text;
alter table public.spare_parts add column if not exists part_code text;

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  type text not null,
  title text not null,
  message text not null,
  related_id text,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.settings (
  key text primary key,
  value text,
  type text not null default 'text',
  description text,
  updated_at timestamptz not null default now()
);

create table if not exists public.store_settings (
  id text primary key,
  store_name text,
  store_address text,
  phone text,
  whatsapp_phone text,
  bank_name text,
  bank_account_number text,
  bank_account_name text,
  qris_image_base64 text,
  pickup_notes text,
  open_hours text,
  updated_at timestamptz not null default now()
);

create table if not exists public.counter_categories (
  id bigint generated by default as identity primary key,
  name text not null,
  icon text,
  color text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.counter_transactions (
  id bigint generated by default as identity primary key,
  transaction_code text unique,
  transaction_date timestamptz not null default now(),
  category_id bigint references public.counter_categories(id) on delete set null,
  category_name text,
  product_name text,
  customer_id bigint references public.customers(id) on delete set null,
  customer_name text,
  customer_phone text,
  customer_info text,
  service_id bigint references public.services(id) on delete set null,
  service_code text,
  ppob_transaction_id bigint,
  ppob_transaction_code text,
  line_items jsonb not null default '[]'::jsonb,
  receipt_payload jsonb not null default '{}'::jsonb,
  modal_price double precision not null default 0,
  selling_price double precision not null default 0,
  profit double precision not null default 0,
  payment_method text,
  receipt_image text,
  ocr_raw_text text,
  notes text,
  created_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.counter_transactions
  add column if not exists transaction_code text unique;
alter table public.counter_transactions
  add column if not exists customer_id bigint references public.customers(id) on delete set null;
alter table public.counter_transactions
  add column if not exists customer_name text;
alter table public.counter_transactions
  add column if not exists customer_phone text;
alter table public.counter_transactions
  add column if not exists service_id bigint references public.services(id) on delete set null;
alter table public.counter_transactions
  add column if not exists service_code text;
alter table public.counter_transactions
  add column if not exists ppob_transaction_id bigint;
alter table public.counter_transactions
  add column if not exists ppob_transaction_code text;
alter table public.counter_transactions
  add column if not exists line_items jsonb not null default '[]'::jsonb;
alter table public.counter_transactions
  add column if not exists receipt_payload jsonb not null default '{}'::jsonb;

create table if not exists public.counter_expenses (
  id bigint generated by default as identity primary key,
  expense_date timestamptz not null default now(),
  description text not null,
  amount double precision not null default 0,
  category text,
  receipt_image text,
  created_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ppob_apps (
  id_aplikasi text primary key,
  nama_aplikasi text not null,
  jenis_layanan text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ppob_categories (
  id_kategori text primary key,
  nama_kategori text not null,
  tipe_transaksi text not null default 'prabayar',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ppob_services (
  id_layanan text primary key,
  category_id text not null references public.ppob_categories(id_kategori) on delete cascade,
  nama_layanan text not null,
  tipe_override text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ppob_transactions (
  id bigint generated by default as identity primary key,
  transaction_code text unique not null,
  provider_app_id text not null references public.ppob_apps(id_aplikasi) on delete restrict,
  provider_app_name text not null,
  category_id text references public.ppob_categories(id_kategori) on delete set null,
  category_name text,
  service_id text references public.ppob_services(id_layanan) on delete set null,
  service_name text,
  transaction_type text not null default 'prabayar',
  customer_info text,
  target_number text,
  token_customer_id text,
  modal_price double precision not null default 0,
  selling_price double precision not null default 0,
  profit double precision not null default 0,
  payment_method text,
  notes text,
  receipt_payload jsonb not null default '{}'::jsonb,
  transaction_date timestamptz not null default now(),
  created_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ppob_daily_balances (
  id bigint generated by default as identity primary key,
  provider_app_id text not null references public.ppob_apps(id_aplikasi) on delete cascade,
  balance_date text not null,
  opening_balance double precision not null default 0,
  closing_balance double precision not null default 0,
  notes text,
  created_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(provider_app_id, balance_date)
);

create table if not exists public.ppob_receipt_settings (
  id text primary key,
  header_image_base64 text,
  header_text text,
  address text,
  footer_text text,
  updated_at timestamptz not null default now()
);

create table if not exists public.ppob_printer_settings (
  id text primary key,
  printer_name text,
  printer_address text,
  paper_size text not null default '58',
  auto_print boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.cf_diagnosis_history (
  id bigint generated by default as identity primary key,
  category_id integer not null,
  category_name text not null,
  device_info text,
  symptoms jsonb not null default '[]'::jsonb,
  results jsonb not null default '[]'::jsonb,
  top_diagnosis text,
  cf_percentage double precision not null default 0,
  user_id uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.diagnosis_configs (
  id text primary key,
  draft_data jsonb,
  draft_file_path text,
  draft_version integer not null default 1,
  draft_updated_at timestamptz,
  draft_updated_by uuid references public.users(id) on delete set null,
  published_file_path text,
  published_version integer not null default 1,
  published_at timestamptz,
  published_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete set null,
  action text not null,
  target_collection text,
  target_id text,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

insert into public.diagnosis_configs (id)
values ('default')
on conflict (id) do nothing;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, email, username, phone, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1)),
    new.raw_user_meta_data ->> 'phone',
    coalesce(new.raw_user_meta_data ->> 'role', 'customer')
  )
  on conflict (id) do update
    set email = excluded.email,
        username = excluded.username,
        phone = excluded.phone,
        role = excluded.role,
        updated_at = now();

  if coalesce(new.raw_user_meta_data ->> 'role', 'customer') = 'customer' then
    insert into public.customers (user_id, name, phone, email)
    values (
      new.id,
      coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1)),
      new.raw_user_meta_data ->> 'phone',
      new.email
    )
    on conflict (user_id) do update
      set name = excluded.name,
          phone = excluded.phone,
          email = excluded.email,
          updated_at = now();
  end if;

  return new;
end;
$$;

create or replace function public.notify_admins(
  p_title text,
  p_message text,
  p_related_id text default null,
  p_type text default 'admin'
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.notifications (user_id, type, title, message, related_id)
  select id, coalesce(p_type, 'admin'), p_title, p_message, p_related_id
  from public.users
  where role = 'admin';
end;
$$;

grant execute on function public.notify_admins(text, text, text, text) to authenticated;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.is_admin(uid uuid)
returns boolean
language sql
stable
as $$
  select exists (
    select 1 from public.users where id = uid and role = 'admin'
  );
$$;

create or replace function public.admin_create_customer_user(
  p_email text,
  p_password text,
  p_username text,
  p_phone text default '',
  p_address text default ''
)
returns uuid
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_admin_id uuid := auth.uid();
  v_user_id uuid := gen_random_uuid();
begin
  if v_admin_id is null or not public.is_admin(v_admin_id) then
    raise exception 'Hanya admin yang dapat membuat akun pelanggan';
  end if;

  if exists (select 1 from auth.users where email = p_email) then
    raise exception 'Email sudah digunakan';
  end if;

  insert into auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    raw_app_meta_data,
    raw_user_meta_data,
    created_at,
    updated_at,
    confirmation_token,
    email_change,
    email_change_token_new,
    recovery_token
  ) values (
    '00000000-0000-0000-0000-000000000000',
    v_user_id,
    'authenticated',
    'authenticated',
    p_email,
    crypt(p_password, gen_salt('bf')),
    now(),
    jsonb_build_object('provider', 'email', 'providers', array['email']),
    jsonb_build_object(
      'username', p_username,
      'display_name', p_username,
      'phone', p_phone,
      'role', 'customer'
    ),
    now(),
    now(),
    '',
    '',
    '',
    ''
  );

  insert into auth.identities (
    id,
    user_id,
    identity_data,
    provider,
    provider_id,
    last_sign_in_at,
    created_at,
    updated_at
  ) values (
    gen_random_uuid(),
    v_user_id,
    jsonb_build_object(
      'sub', v_user_id::text,
      'email', p_email,
      'email_verified', true,
      'phone_verified', false
    ),
    'email',
    v_user_id::text,
    now(),
    now(),
    now()
  );

  insert into public.users (id, email, username, phone, role)
  values (v_user_id, p_email, p_username, p_phone, 'customer')
  on conflict (id) do nothing;

  insert into public.customers (user_id, name, phone, email, address)
  values (v_user_id, p_username, p_phone, p_email, p_address)
  on conflict (user_id) do update
    set name = excluded.name,
        phone = excluded.phone,
        email = excluded.email,
        address = excluded.address,
        updated_at = now();

  return v_user_id;
end;
$$;

create or replace function public.admin_create_admin_user(
  p_email text,
  p_password text,
  p_username text,
  p_phone text default ''
)
returns uuid
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_admin_id uuid := auth.uid();
  v_user_id uuid := gen_random_uuid();
begin
  if v_admin_id is null or not public.is_admin(v_admin_id) then
    raise exception 'Hanya admin yang dapat membuat akun admin';
  end if;

  if exists (select 1 from auth.users where email = p_email) then
    raise exception 'Email sudah digunakan';
  end if;

  insert into auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    raw_app_meta_data,
    raw_user_meta_data,
    created_at,
    updated_at,
    confirmation_token,
    email_change,
    email_change_token_new,
    recovery_token
  ) values (
    '00000000-0000-0000-0000-000000000000',
    v_user_id,
    'authenticated',
    'authenticated',
    p_email,
    crypt(p_password, gen_salt('bf')),
    now(),
    jsonb_build_object('provider', 'email', 'providers', array['email']),
    jsonb_build_object(
      'username', p_username,
      'display_name', p_username,
      'phone', p_phone,
      'role', 'admin'
    ),
    now(),
    now(),
    '',
    '',
    '',
    ''
  );

  insert into auth.identities (
    id,
    user_id,
    identity_data,
    provider,
    provider_id,
    last_sign_in_at,
    created_at,
    updated_at
  ) values (
    gen_random_uuid(),
    v_user_id,
    jsonb_build_object(
      'sub', v_user_id::text,
      'email', p_email,
      'email_verified', true,
      'phone_verified', false
    ),
    'email',
    v_user_id::text,
    now(),
    now(),
    now()
  );

  insert into public.users (id, email, username, phone, role)
  values (v_user_id, p_email, p_username, p_phone, 'admin')
  on conflict (id) do nothing;

  return v_user_id;
end;
$$;

create or replace function public.bootstrap_defaults()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.store_settings (id, store_name, open_hours)
  values ('config', 'DigiTech Service Center', 'Senin - Sabtu, 08:00 - 17:00')
  on conflict (id) do nothing;

  insert into public.counter_categories (name, icon, color, sort_order, is_active)
  values
    ('Pulsa', 'phone_android', '#FF6B35', 1, true),
    ('Paket Data', 'wifi', '#3B82F6', 2, true),
    ('Token Listrik', 'bolt', '#F59E0B', 3, true),
    ('Voucher Game', 'sports_esports', '#8B5CF6', 4, true),
    ('Tagihan', 'receipt_long', '#22C55E', 5, true)
  on conflict do nothing;
end;
$$;

create index if not exists idx_bookings_customer_id on public.bookings(customer_id);
create index if not exists idx_bookings_status on public.bookings(status);
create index if not exists idx_services_customer_id on public.services(customer_id);
create index if not exists idx_services_status on public.services(status);
create index if not exists idx_notifications_user_id on public.notifications(user_id);
create index if not exists idx_transactions_service_id on public.transactions(service_id);
create index if not exists idx_counter_transactions_date on public.counter_transactions(transaction_date);
create unique index if not exists idx_counter_transactions_code on public.counter_transactions(transaction_code);
create index if not exists idx_counter_expenses_date on public.counter_expenses(expense_date);
create index if not exists idx_ppob_transactions_app_date on public.ppob_transactions(provider_app_id, transaction_date);
create index if not exists idx_ppob_daily_balances_app_date on public.ppob_daily_balances(provider_app_id, balance_date);

drop trigger if exists trg_users_updated_at on public.users;
create trigger trg_users_updated_at before update on public.users
for each row execute procedure public.set_updated_at();
drop trigger if exists trg_customers_updated_at on public.customers;
create trigger trg_customers_updated_at before update on public.customers
for each row execute procedure public.set_updated_at();
drop trigger if exists trg_bookings_updated_at on public.bookings;
create trigger trg_bookings_updated_at before update on public.bookings
for each row execute procedure public.set_updated_at();
drop trigger if exists trg_services_updated_at on public.services;
create trigger trg_services_updated_at before update on public.services
for each row execute procedure public.set_updated_at();
drop trigger if exists trg_transactions_updated_at on public.transactions;
create trigger trg_transactions_updated_at before update on public.transactions
for each row execute procedure public.set_updated_at();
drop trigger if exists trg_spare_parts_updated_at on public.spare_parts;
create trigger trg_spare_parts_updated_at before update on public.spare_parts
for each row execute procedure public.set_updated_at();
drop trigger if exists trg_settings_updated_at on public.settings;
create trigger trg_settings_updated_at before update on public.settings
for each row execute procedure public.set_updated_at();
drop trigger if exists trg_store_settings_updated_at on public.store_settings;
create trigger trg_store_settings_updated_at before update on public.store_settings
for each row execute procedure public.set_updated_at();
drop trigger if exists trg_counter_categories_updated_at on public.counter_categories;
create trigger trg_counter_categories_updated_at before update on public.counter_categories
for each row execute procedure public.set_updated_at();
drop trigger if exists trg_counter_transactions_updated_at on public.counter_transactions;
create trigger trg_counter_transactions_updated_at before update on public.counter_transactions
for each row execute procedure public.set_updated_at();
drop trigger if exists trg_counter_expenses_updated_at on public.counter_expenses;
create trigger trg_counter_expenses_updated_at before update on public.counter_expenses
for each row execute procedure public.set_updated_at();
drop trigger if exists trg_ppob_apps_updated_at on public.ppob_apps;
create trigger trg_ppob_apps_updated_at before update on public.ppob_apps
for each row execute procedure public.set_updated_at();
drop trigger if exists trg_ppob_categories_updated_at on public.ppob_categories;
create trigger trg_ppob_categories_updated_at before update on public.ppob_categories
for each row execute procedure public.set_updated_at();
drop trigger if exists trg_ppob_services_updated_at on public.ppob_services;
create trigger trg_ppob_services_updated_at before update on public.ppob_services
for each row execute procedure public.set_updated_at();
drop trigger if exists trg_ppob_transactions_updated_at on public.ppob_transactions;
create trigger trg_ppob_transactions_updated_at before update on public.ppob_transactions
for each row execute procedure public.set_updated_at();
drop trigger if exists trg_ppob_daily_balances_updated_at on public.ppob_daily_balances;
create trigger trg_ppob_daily_balances_updated_at before update on public.ppob_daily_balances
for each row execute procedure public.set_updated_at();
drop trigger if exists trg_ppob_receipt_settings_updated_at on public.ppob_receipt_settings;
create trigger trg_ppob_receipt_settings_updated_at before update on public.ppob_receipt_settings
for each row execute procedure public.set_updated_at();
drop trigger if exists trg_ppob_printer_settings_updated_at on public.ppob_printer_settings;
create trigger trg_ppob_printer_settings_updated_at before update on public.ppob_printer_settings
for each row execute procedure public.set_updated_at();
drop trigger if exists trg_diagnosis_configs_updated_at on public.diagnosis_configs;
create trigger trg_diagnosis_configs_updated_at before update on public.diagnosis_configs
for each row execute procedure public.set_updated_at();

alter table public.users enable row level security;
alter table public.customers enable row level security;
alter table public.bookings enable row level security;
alter table public.services enable row level security;
alter table public.transactions enable row level security;
alter table public.spare_parts enable row level security;
alter table public.notifications enable row level security;
alter table public.settings enable row level security;
alter table public.store_settings enable row level security;
alter table public.counter_categories enable row level security;
alter table public.counter_transactions enable row level security;
alter table public.counter_expenses enable row level security;
alter table public.ppob_apps enable row level security;
alter table public.ppob_categories enable row level security;
alter table public.ppob_services enable row level security;
alter table public.ppob_transactions enable row level security;
alter table public.ppob_daily_balances enable row level security;
alter table public.ppob_receipt_settings enable row level security;
alter table public.ppob_printer_settings enable row level security;
alter table public.cf_diagnosis_history enable row level security;
alter table public.diagnosis_configs enable row level security;
alter table public.activity_logs enable row level security;

drop policy if exists "users admin full" on public.users;
create policy "users admin full" on public.users
for all to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "users own select" on public.users;
create policy "users own select" on public.users
for select to authenticated
using (id = auth.uid());

drop policy if exists "users own update" on public.users;
create policy "users own update" on public.users
for update to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists "customers admin full" on public.customers;
create policy "customers admin full" on public.customers
for all to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "customers own read" on public.customers;
create policy "customers own read" on public.customers
for select to authenticated
using (user_id = auth.uid());

drop policy if exists "bookings admin full" on public.bookings;
create policy "bookings admin full" on public.bookings
for all to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "bookings own full" on public.bookings;
create policy "bookings own full" on public.bookings
for all to authenticated
using (customer_id = auth.uid())
with check (customer_id = auth.uid());

drop policy if exists "services admin full" on public.services;
create policy "services admin full" on public.services
for all to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "services own read" on public.services;
create policy "services own read" on public.services
for select to authenticated
using (customer_id = auth.uid());

drop policy if exists "services own update payment" on public.services;
create policy "services own update payment" on public.services
for update to authenticated
using (customer_id = auth.uid())
with check (customer_id = auth.uid());

drop policy if exists "transactions admin full" on public.transactions;
create policy "transactions admin full" on public.transactions
for all to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "spare parts admin full" on public.spare_parts;
create policy "spare parts admin full" on public.spare_parts
for all to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "notifications admin full" on public.notifications;
create policy "notifications admin full" on public.notifications
for all to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "notifications own read update" on public.notifications;
create policy "notifications own read update" on public.notifications
for select to authenticated
using (user_id = auth.uid());

drop policy if exists "notifications own update" on public.notifications;
create policy "notifications own update" on public.notifications
for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "settings admin full" on public.settings;
create policy "settings admin full" on public.settings
for all to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop table if exists public.password_requests cascade;

drop policy if exists "store settings read all auth" on public.store_settings;
create policy "store settings read all auth" on public.store_settings
for select to authenticated
using (true);

drop policy if exists "store settings admin write" on public.store_settings;
create policy "store settings admin write" on public.store_settings
for all to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "counter categories read all auth" on public.counter_categories;
create policy "counter categories read all auth" on public.counter_categories
for select to authenticated
using (true);

drop policy if exists "counter categories admin write" on public.counter_categories;
create policy "counter categories admin write" on public.counter_categories
for all to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "counter tx admin full" on public.counter_transactions;
create policy "counter tx admin full" on public.counter_transactions
for all to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "counter expenses admin full" on public.counter_expenses;
create policy "counter expenses admin full" on public.counter_expenses
for all to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "ppob apps read all auth" on public.ppob_apps;
create policy "ppob apps read all auth" on public.ppob_apps
for select to authenticated
using (true);

drop policy if exists "ppob apps admin write" on public.ppob_apps;
create policy "ppob apps admin write" on public.ppob_apps
for all to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "ppob categories read all auth" on public.ppob_categories;
create policy "ppob categories read all auth" on public.ppob_categories
for select to authenticated
using (true);

drop policy if exists "ppob categories admin write" on public.ppob_categories;
create policy "ppob categories admin write" on public.ppob_categories
for all to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "ppob services read all auth" on public.ppob_services;
create policy "ppob services read all auth" on public.ppob_services
for select to authenticated
using (true);

drop policy if exists "ppob services admin write" on public.ppob_services;
create policy "ppob services admin write" on public.ppob_services
for all to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "ppob tx admin full" on public.ppob_transactions;
create policy "ppob tx admin full" on public.ppob_transactions
for all to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "ppob balances admin full" on public.ppob_daily_balances;
create policy "ppob balances admin full" on public.ppob_daily_balances
for all to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "ppob receipt settings admin full" on public.ppob_receipt_settings;
create policy "ppob receipt settings admin full" on public.ppob_receipt_settings
for all to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "ppob printer settings admin full" on public.ppob_printer_settings;
create policy "ppob printer settings admin full" on public.ppob_printer_settings
for all to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "diagnosis history admin full" on public.cf_diagnosis_history;
create policy "diagnosis history admin full" on public.cf_diagnosis_history
for all to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "diagnosis history own insert" on public.cf_diagnosis_history;
create policy "diagnosis history own insert" on public.cf_diagnosis_history
for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists "diagnosis history own read" on public.cf_diagnosis_history;
create policy "diagnosis history own read" on public.cf_diagnosis_history
for select to authenticated
using (user_id = auth.uid());

drop policy if exists "diagnosis config public read" on public.diagnosis_configs;
create policy "diagnosis config public read" on public.diagnosis_configs
for select
using (true);

drop policy if exists "diagnosis config admin write" on public.diagnosis_configs;
create policy "diagnosis config admin write" on public.diagnosis_configs
for all to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "activity logs admin full" on public.activity_logs;
create policy "activity logs admin full" on public.activity_logs
for all to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

insert into storage.buckets (id, name, public)
values ('diagnosis-data', 'diagnosis-data', true)
on conflict (id) do update
set public = excluded.public;

drop policy if exists "diagnosis storage public read" on storage.objects;
create policy "diagnosis storage public read" on storage.objects
for select
using (bucket_id = 'diagnosis-data');

drop policy if exists "diagnosis storage admin write" on storage.objects;
create policy "diagnosis storage admin write" on storage.objects
for all to authenticated
using (
  bucket_id = 'diagnosis-data'
  and public.is_admin(auth.uid())
)
with check (
  bucket_id = 'diagnosis-data'
  and public.is_admin(auth.uid())
);

select public.bootstrap_defaults();
